/**
 * BAP-10's pure, fail-closed transition authority.  It deliberately has no
 * persistence, provider, adapter, or orchestration dependencies.
 */
import type { ProcessingAttempt, PublicDraft, PublishedRecord, PublishAttempt, ReviewDecision, SourceRevisionSignal } from './publication-contract';

export const PUBLICATION_STAGES = ['pending', 'selected', 'processing', 'validating', 'repairing', 'review_ready', 'in_review', 'approved', 'publish_ready', 'publishing', 'published', 'publication_failed', 'needs_human_intervention'] as const;
export type PublicationStage = (typeof PUBLICATION_STAGES)[number];
export type NextRecovery = 'repair' | 'regenerate';
export type TransitionErrorCode = 'DUPLICATE_CONFLICT' | 'ITEM_MISMATCH' | 'CORRELATION_MISMATCH' | 'STALE_VERSION' | 'ILLEGAL_TRANSITION' | 'STALE_PIN' | 'ACTIVE_OPERATION_MISMATCH' | 'BUDGET_EXHAUSTED' | 'INVALID_INPUT';

export interface Evidence { readonly status?: 'passed' | 'failed'; readonly code: string; readonly summary: string; }
export interface ValidationPin { readonly draftId: string; readonly draftVersion: number; readonly draftHash: string; readonly evidence: Evidence; }
export interface ActiveOperation { readonly id: string; readonly kind: 'generate' | 'repair' | 'regenerate' | 'publish'; readonly draftId: string | null; readonly approvalId: string | null; readonly confirmationId: string | null; readonly destinationId: string | null; readonly destinationContractVersion: string | null; }
export interface TransitionAudit {
	readonly id: string; readonly kind: 'transition' | 'source_revision'; readonly triggerId: string; readonly triggerType: TransitionKind;
	readonly from: PublicationStage; readonly to: PublicationStage; readonly versionBefore: number; readonly versionAfter: number;
	readonly correlationId: string; readonly occurredAt: string; readonly actorId: string; readonly pins: Readonly<Record<string, string | number | null>>;
	readonly budgetsBefore: AttemptBudget; readonly budgetsAfter: AttemptBudget; readonly resultEvidence: Readonly<Record<string, unknown>>;
}
export interface AttemptBudget { readonly repairs: number; readonly regenerations: number; }
export interface PublicationWorkflowState {
	readonly item: { readonly id: string; readonly correlationId: string; readonly version: number; readonly stage: PublicationStage; readonly currentDraftId: string | null; readonly updatedAt: string };
	readonly budgets: AttemptBudget; readonly nextRecovery: NextRecovery | null; readonly activeOperation: ActiveOperation | null;
	readonly sourceBaseline: { readonly id: string; readonly path: string; readonly contentHash: string };
	readonly currentValidation: ValidationPin | null;
	readonly approval: { readonly reviewDecisionId: string; readonly draftId: string; readonly draftVersion: number; readonly draftHash: string } | null;
	readonly confirmation: { readonly id: string; readonly draftId: string; readonly reviewDecisionId: string; readonly destinationId: string; readonly destinationContractVersion: string; readonly confirmedBy: string; readonly confirmedAt: string } | null;
	readonly processingAttempts: readonly ProcessingAttempt[]; readonly drafts: readonly PublicDraft[]; readonly reviewDecisions: readonly ReviewDecision[];
	readonly publishAttempts: readonly PublishAttempt[]; readonly publishedRecords: readonly PublishedRecord[]; readonly sourceRevisionSignals: readonly SourceRevisionSignal[];
	readonly audit: readonly TransitionAudit[]; readonly receipts: Readonly<Record<string, { readonly fingerprint: string }>>;
}
export type TransitionKind = 'select_publication' | 'start_generation' | 'processing_produced' | 'processing_failed' | 'validation_passed' | 'validation_failed' | 'start_repair' | 'start_regeneration' | 'begin_review' | 'approve_review' | 'submit_human_revision' | 'request_changes' | 'revise_approved_draft' | 'confirm_publication' | 'revise_confirmed_draft' | 'start_publish' | 'publish_succeeded' | 'publish_failed' | 'reconfirm_publication' | 'escalate_publication_failure' | 'observe_source_revision';
export interface TransitionInput {
	readonly id: string; readonly itemId: string; readonly correlationId: string; readonly expectedVersion: number; readonly kind: TransitionKind;
	readonly occurredAt: string; readonly actorId: string; readonly operationId?: string; readonly draft?: PublicDraft; readonly processingAttempt?: ProcessingAttempt;
	readonly reviewDecision?: ReviewDecision; readonly publishAttempt?: PublishAttempt; readonly publishedRecord?: PublishedRecord; readonly sourceRevisionSignal?: SourceRevisionSignal;
	readonly reviewDecisionId?: string; readonly draftId?: string; readonly draftVersion?: number; readonly draftHash?: string;
	readonly destinationId?: string; readonly destinationContractVersion?: string; readonly confirmationId?: string; readonly confirmedBy?: string; readonly confirmedAt?: string;
	readonly validation?: { readonly draftId: string; readonly draftVersion: number; readonly draftHash: string; readonly passed: boolean; readonly code: string; readonly summary: string };
	readonly evidence?: Evidence;
}
export type TransitionResult = { readonly ok: true; readonly state: PublicationWorkflowState; readonly duplicate: boolean } | { readonly ok: false; readonly code: TransitionErrorCode; readonly message: string };

const rows: readonly [PublicationStage, PublicationStage, TransitionKind][] = [
	['pending', 'selected', 'select_publication'], ['selected', 'processing', 'start_generation'], ['processing', 'validating', 'processing_produced'], ['processing', 'needs_human_intervention', 'processing_failed'], ['validating', 'review_ready', 'validation_passed'], ['validating', 'repairing', 'validation_failed'], ['validating', 'needs_human_intervention', 'validation_failed'], ['repairing', 'processing', 'start_repair'], ['repairing', 'processing', 'start_regeneration'], ['review_ready', 'in_review', 'begin_review'], ['in_review', 'approved', 'approve_review'], ['in_review', 'validating', 'submit_human_revision'], ['in_review', 'repairing', 'request_changes'], ['in_review', 'needs_human_intervention', 'request_changes'], ['approved', 'validating', 'revise_approved_draft'], ['approved', 'publish_ready', 'confirm_publication'], ['publish_ready', 'validating', 'revise_confirmed_draft'], ['publish_ready', 'publishing', 'start_publish'], ['publishing', 'published', 'publish_succeeded'], ['publishing', 'publication_failed', 'publish_failed'], ['publication_failed', 'publish_ready', 'reconfirm_publication'], ['publication_failed', 'needs_human_intervention', 'escalate_publication_failure'], ['needs_human_intervention', 'validating', 'submit_human_revision'],
];
export const LEGAL_TRANSITIONS = rows.map(([from, to, kind]) => ({ from, to, kind }));
const failed = (code: TransitionErrorCode, message: string): TransitionResult => ({ ok: false, code, message });
const canonical = (value: unknown): string => {
	if (value === null || typeof value !== 'object') return JSON.stringify(value);
	if (Array.isArray(value)) return `[${value.map(canonical).join(',')}]`;
	const record = value as Record<string, unknown>;
	return `{${Object.keys(record).sort().map((key) => `${JSON.stringify(key)}:${canonical(record[key])}`).join(',')}}`;
};
const fingerprint = (input: TransitionInput): string => canonical(input);
const pins = (input: TransitionInput): Record<string, string | number | null> => ({ draftId: input.draftId ?? input.draft?.id ?? null, draftVersion: input.draftVersion ?? input.draft?.version ?? null, draftHash: input.draftHash ?? input.draft?.contentHash ?? null, reviewDecisionId: input.reviewDecisionId ?? input.reviewDecision?.id ?? null, confirmationId: input.confirmationId ?? null, destinationId: input.destinationId ?? input.publishAttempt?.destinationId ?? null, destinationContractVersion: input.destinationContractVersion ?? input.publishAttempt?.destinationContractVersion ?? null, operationId: input.operationId ?? null });
const auditEvidence = (input: TransitionInput): Record<string, unknown> => {
	if (input.validation) return { type: 'validation', draftId: input.validation.draftId, draftVersion: input.validation.draftVersion, draftHash: input.validation.draftHash, status: input.validation.passed ? 'passed' : 'failed', code: input.validation.code, summary: input.validation.summary };
	if (input.processingAttempt) { const outcome = input.processingAttempt.outcome; return { type: 'processing_attempt', attemptId: input.processingAttempt.id, sequence: input.processingAttempt.sequence, operationKind: input.processingAttempt.kind, inputDraftId: input.processingAttempt.inputDraftId, outcomeStatus: outcome.status, draftId: outcome.status === 'produced' ? outcome.publicDraftId : null, code: outcome.status === 'produced' ? outcome.validation.code : outcome.failure.code, summary: outcome.status === 'produced' ? outcome.validation.summary : outcome.failure.summary }; }
	if (input.reviewDecision) return { type: 'review_decision', reviewDecisionId: input.reviewDecision.id, decision: input.reviewDecision.decision, draftId: input.reviewDecision.publicDraftId, draftVersion: input.reviewDecision.publicDraftVersion, draftHash: input.reviewDecision.publicDraftContentHash, summary: input.reviewDecision.summary };
	if (input.publishAttempt) { const outcome = input.publishAttempt.outcome; return { type: 'publish_attempt', publishAttemptId: input.publishAttempt.id, sequence: input.publishAttempt.sequence, outcomeStatus: outcome.status, destinationId: input.publishAttempt.destinationId, destinationContractVersion: input.publishAttempt.destinationContractVersion, receiptHash: outcome.status === 'succeeded' ? outcome.receiptHash : null, destinationReference: outcome.status === 'succeeded' ? outcome.destinationReference : null, code: outcome.status === 'succeeded' ? 'PUBLISH_SUCCEEDED' : outcome.failure.code, summary: outcome.status === 'succeeded' ? 'publication receipt recorded' : outcome.failure.summary }; }
	if (input.sourceRevisionSignal) return { type: 'source_revision_signal', signalId: input.sourceRevisionSignal.id, sequence: input.sourceRevisionSignal.sequence, kind: input.sourceRevisionSignal.kind, baselinePath: input.sourceRevisionSignal.baselinePath, baselineContentHash: input.sourceRevisionSignal.baselineContentHash, observedPath: input.sourceRevisionSignal.observedPath, observedContentHash: input.sourceRevisionSignal.observedContentHash };
	if (input.confirmationId || input.destinationId || input.destinationContractVersion) return { type: 'confirmation', confirmationId: input.confirmationId ?? null, reviewDecisionId: input.reviewDecisionId ?? null, draftId: input.draftId ?? null, draftVersion: input.draftVersion ?? null, draftHash: input.draftHash ?? null, destinationId: input.destinationId ?? null, destinationContractVersion: input.destinationContractVersion ?? null, confirmedBy: input.confirmedBy ?? null, confirmedAt: input.confirmedAt ?? null };
	if (input.evidence) return { type: 'explicit', status: input.evidence.status ?? 'accepted', code: input.evidence.code, summary: input.evidence.summary };
	return { type: 'transition', status: 'accepted', code: 'TRANSITION_ACCEPTED', summary: input.kind };
};
const withAudit = (state: PublicationWorkflowState, input: TransitionInput, to: PublicationStage, changes: Partial<PublicationWorkflowState> = {}): PublicationWorkflowState => {
	const before = state.item.version; const budgets = changes.budgets ?? state.budgets;
	const next: PublicationWorkflowState = { ...state, ...changes, item: { ...state.item, ...(changes.item ?? {}), stage: to, version: before + 1, updatedAt: input.occurredAt }, audit: state.audit, receipts: state.receipts };
	const entry: TransitionAudit = { id: `audit:${input.id}`, kind: input.kind === 'observe_source_revision' ? 'source_revision' : 'transition', triggerId: input.id, triggerType: input.kind, from: state.item.stage, to, versionBefore: before, versionAfter: before + 1, correlationId: state.item.correlationId, occurredAt: input.occurredAt, actorId: input.actorId, pins: pins(input), budgetsBefore: state.budgets, budgetsAfter: budgets, resultEvidence: auditEvidence(input) };
	return { ...next, audit: [...state.audit, entry], receipts: { ...state.receipts, [input.id]: { fingerprint: fingerprint(input) } } };
};
const exactApproval = (state: PublicationWorkflowState, input: TransitionInput): boolean => state.approval !== null && input.reviewDecisionId === state.approval.reviewDecisionId && input.draftId === state.approval.draftId && input.draftVersion === state.approval.draftVersion && input.draftHash === state.approval.draftHash;
const validEntity = (entity: { readonly publicationItemId: string; readonly correlationId: string } | undefined, state: PublicationWorkflowState): boolean => entity !== undefined && entity.publicationItemId === state.item.id && entity.correlationId === state.item.correlationId;
const nextSequence = (records: readonly { readonly sequence: number }[]): number => records.length + 1;
const unused = (id: string, ...collections: readonly (readonly { readonly id: string }[])[]): boolean => collections.every((values) => !values.some((value) => value.id === id));
const validUtc = (value: string | undefined): value is string => value !== undefined && !Number.isNaN(new Date(value).valueOf()) && new Date(value).toISOString() === value;
const ordered = (earlier: string, later: string): boolean => new Date(later).valueOf() >= new Date(earlier).valueOf();
const validEvidenceTimes = (input: TransitionInput): boolean => {
	if (!validUtc(input.occurredAt) || (input.confirmedAt !== undefined && !validUtc(input.confirmedAt))) return false;
	if (input.draft && !validUtc(input.draft.createdAt)) return false;
	if (input.processingAttempt && (!validUtc(input.processingAttempt.startedAt) || !validUtc(input.processingAttempt.completedAt) || !ordered(input.processingAttempt.startedAt, input.processingAttempt.completedAt))) return false;
	if (input.reviewDecision && !validUtc(input.reviewDecision.decidedAt)) return false;
	if (input.publishAttempt && (!validUtc(input.publishAttempt.confirmedAt) || !validUtc(input.publishAttempt.startedAt) || !validUtc(input.publishAttempt.completedAt) || !ordered(input.publishAttempt.confirmedAt, input.publishAttempt.startedAt) || !ordered(input.publishAttempt.startedAt, input.publishAttempt.completedAt))) return false;
	if (input.publishedRecord && (!validUtc(input.publishedRecord.publishedAt) || (input.publishAttempt !== undefined && !ordered(input.publishAttempt.completedAt, input.publishedRecord.publishedAt)))) return false;
	if (input.sourceRevisionSignal && !validUtc(input.sourceRevisionSignal.detectedAt)) return false;
	return true;
};

/** Applies exactly one command/event. Failed results are side-effect free. */
export function transitionPublication(state: PublicationWorkflowState, input: TransitionInput): TransitionResult {
	const prior = state.receipts[input.id]; if (prior) return prior.fingerprint === fingerprint(input) ? { ok: true, state, duplicate: true } : failed('DUPLICATE_CONFLICT', 'trigger id was reused with different payload');
	if (input.itemId !== state.item.id) return failed('ITEM_MISMATCH', 'input item does not match aggregate');
	if (input.correlationId !== state.item.correlationId) return failed('CORRELATION_MISMATCH', 'input correlation does not match aggregate');
	if (input.expectedVersion !== state.item.version) return failed('STALE_VERSION', 'expected item version is stale');
	if (!input.id || !input.actorId || !validEvidenceTimes(input)) return failed('INVALID_INPUT', 'all supplied timestamps must be exact UTC ISO values in causal order');
	if (input.kind === 'observe_source_revision') {
		const signal = input.sourceRevisionSignal;
		if (!validEntity(signal, state) || !signal || !(['content-changed', 'path-changed', 'source-missing'] as const).includes(signal.kind) || !unused(signal.id, state.sourceRevisionSignals) || signal.sequence !== nextSequence(state.sourceRevisionSignals) || signal.sourceNoteRefId !== state.sourceBaseline.id || signal.baselinePath !== state.sourceBaseline.path || signal.baselineContentHash !== state.sourceBaseline.contentHash || (signal.kind === 'source-missing' ? signal.observedPath !== null || signal.observedContentHash !== null : signal.kind === 'content-changed' ? signal.observedPath === null || signal.observedContentHash === null || signal.observedContentHash === signal.baselineContentHash : signal.observedPath === null || signal.observedContentHash === null || signal.observedPath === signal.baselinePath)) return failed('STALE_PIN', 'source signal must exactly preserve the source baseline and shape');
		const sourceStages: readonly PublicationStage[] = ['pending', 'selected', 'processing', 'validating', 'repairing', 'review_ready', 'in_review', 'approved', 'publish_ready', 'publication_failed'];
		const to = sourceStages.includes(state.item.stage) ? 'needs_human_intervention' : state.item.stage;
		return { ok: true, state: withAudit(state, input, to, { sourceRevisionSignals: [...state.sourceRevisionSignals, signal] }), duplicate: false };
	}
	let to = rows.find(([from, target, kind]) => from === state.item.stage && kind === input.kind)?.[1];
	if (!to) return failed('ILLEGAL_TRANSITION', `${input.kind} cannot run from ${state.item.stage}`);
	let changes: Partial<PublicationWorkflowState> = {};
	if (input.kind === 'start_generation' || input.kind === 'start_repair' || input.kind === 'start_regeneration' || input.kind === 'start_publish') {
		if (!input.operationId || state.activeOperation !== null) return failed('ACTIVE_OPERATION_MISMATCH', 'a unique operation id is required and no operation may already be active');
		if (input.kind === 'start_repair' && (state.nextRecovery !== 'repair' || state.budgets.repairs >= 2)) return failed('BUDGET_EXHAUSTED', 'repair is not available');
		if (input.kind === 'start_regeneration' && (state.nextRecovery !== 'regenerate' || state.budgets.repairs !== 2 || state.budgets.regenerations >= 1)) return failed('BUDGET_EXHAUSTED', 'regeneration is not available');
		if (input.kind === 'start_publish' && (!exactApproval(state, input) || state.confirmation === null || state.confirmation.id !== input.confirmationId || state.confirmation.draftId !== input.draftId || state.confirmation.reviewDecisionId !== input.reviewDecisionId || state.confirmation.destinationId !== input.destinationId || state.confirmation.destinationContractVersion !== input.destinationContractVersion)) return failed('STALE_PIN', 'publishing requires exact approval and confirmation pins');
		const kind = input.kind === 'start_generation' ? 'generate' : input.kind === 'start_repair' ? 'repair' : input.kind === 'start_regeneration' ? 'regenerate' : 'publish';
		changes = { activeOperation: { id: input.operationId, kind, draftId: input.kind === 'start_publish' ? input.draftId! : state.item.currentDraftId, approvalId: input.kind === 'start_publish' ? input.reviewDecisionId! : null, confirmationId: input.kind === 'start_publish' ? input.confirmationId! : null, destinationId: input.kind === 'start_publish' ? input.destinationId! : null, destinationContractVersion: input.kind === 'start_publish' ? input.destinationContractVersion! : null } };
	}
	if (input.kind === 'processing_produced') { const operation = state.activeOperation; const attempt = input.processingAttempt; const produced = input.draft; if (!operation || operation.id !== input.operationId || operation.kind === 'publish' || !validEntity(attempt, state) || !validEntity(produced, state) || !attempt || !produced || !unused(attempt.id, state.processingAttempts) || !unused(produced.id, state.drafts) || attempt.sequence !== nextSequence(state.processingAttempts) || attempt.kind !== operation.kind || attempt.sourceNoteRefId !== state.sourceBaseline.id || attempt.inputDraftId !== operation.draftId || attempt.outcome.status !== 'produced' || attempt.outcome.publicDraftId !== produced.id || produced.origin !== 'processing' || produced.processingAttemptId !== attempt.id || produced.sourceNoteRefId !== state.sourceBaseline.id || produced.version !== state.drafts.length + 1 || produced.parentDraftId !== state.item.currentDraftId) return failed('ACTIVE_OPERATION_MISMATCH', 'produced result must match active operation and exact draft provenance'); changes = { processingAttempts: [...state.processingAttempts, attempt], drafts: [...state.drafts, produced], activeOperation: null, nextRecovery: null, approval: null, confirmation: null, currentValidation: null, item: { ...state.item, currentDraftId: produced.id } }; }
	if (input.kind === 'processing_failed') { const operation = state.activeOperation; const attempt = input.processingAttempt; if (!operation || operation.id !== input.operationId || operation.kind === 'publish' || !validEntity(attempt, state) || !attempt || !unused(attempt.id, state.processingAttempts) || attempt.sequence !== nextSequence(state.processingAttempts) || attempt.kind !== operation.kind || attempt.sourceNoteRefId !== state.sourceBaseline.id || attempt.inputDraftId !== operation.draftId || attempt.outcome.status !== 'failed') return failed('ACTIVE_OPERATION_MISMATCH', 'failed result must match active operation'); changes = { processingAttempts: [...state.processingAttempts, attempt], activeOperation: null }; }
	if (input.kind === 'validation_passed' || input.kind === 'validation_failed') { const validation = input.validation; const draft = state.drafts.find((value) => value.id === state.item.currentDraftId); const attempt = draft?.processingAttemptId ? state.processingAttempts.find((value) => value.id === draft.processingAttemptId) : undefined; const expected = attempt?.outcome.status === 'produced' ? attempt.outcome.validation : undefined; if (!validation || !draft || validation.draftId !== draft.id || validation.draftVersion !== draft.version || validation.draftHash !== draft.contentHash || validation.passed !== (input.kind === 'validation_passed') || (expected !== undefined && (expected.passed !== validation.passed || expected.code !== validation.code || expected.summary !== validation.summary))) return failed('STALE_PIN', 'validation must pin the exact current draft and processing evidence'); changes = { currentValidation: { draftId: draft.id, draftVersion: draft.version, draftHash: draft.contentHash, evidence: { status: validation.passed ? 'passed' : 'failed', code: validation.code, summary: validation.summary } } }; if (input.kind === 'validation_failed') { const repair = state.budgets.repairs < 2; const regen = state.budgets.repairs === 2 && state.budgets.regenerations < 1; to = repair || regen ? 'repairing' : 'needs_human_intervention'; changes = { ...changes, nextRecovery: repair ? 'repair' : regen ? 'regenerate' : null }; } }
	if (input.kind === 'begin_review') { const validation = state.currentValidation; if (!validation || validation.evidence.status !== 'passed' || validation.draftId !== state.item.currentDraftId) return failed('STALE_PIN', 'review requires passing validation of current draft'); }
	if (input.kind === 'request_changes') { const draft = state.drafts.find((value) => value.id === state.item.currentDraftId); const decision = input.reviewDecision; if (!validEntity(decision, state) || !decision || !unused(decision.id, state.reviewDecisions) || decision.decision !== 'changes-requested' || !draft || decision.publicDraftId !== draft.id || decision.publicDraftVersion !== draft.version || decision.publicDraftContentHash !== draft.contentHash) return failed('STALE_PIN', 'requested changes require exact current-draft review evidence'); const repair = state.budgets.repairs < 2; const regen = state.budgets.repairs === 2 && state.budgets.regenerations < 1; to = repair || regen ? 'repairing' : 'needs_human_intervention'; changes = { reviewDecisions: [...state.reviewDecisions, decision], nextRecovery: repair ? 'repair' : regen ? 'regenerate' : null }; }
	if (input.kind === 'start_repair') changes = { ...changes, budgets: { ...state.budgets, repairs: state.budgets.repairs + 1 } };
	if (input.kind === 'start_regeneration') changes = { ...changes, budgets: { ...state.budgets, regenerations: state.budgets.regenerations + 1 } };
	if (input.kind === 'approve_review') { const draft = state.drafts.find((value) => value.id === state.item.currentDraftId); if (!validEntity(input.reviewDecision, state) || !input.reviewDecision || !unused(input.reviewDecision.id, state.reviewDecisions) || !draft || input.reviewDecision.decision !== 'approved' || input.reviewDecision.publicDraftId !== draft.id || input.reviewDecision.publicDraftVersion !== draft.version || input.reviewDecision.publicDraftContentHash !== draft.contentHash) return failed('STALE_PIN', 'approval must pin the current exact draft'); changes = { reviewDecisions: [...state.reviewDecisions, input.reviewDecision], approval: { reviewDecisionId: input.reviewDecision.id, draftId: draft.id, draftVersion: draft.version, draftHash: draft.contentHash }, confirmation: null }; }
	if (input.kind === 'submit_human_revision' || input.kind === 'revise_approved_draft' || input.kind === 'revise_confirmed_draft') { const draft = input.draft; if (!validEntity(draft, state) || !draft || !unused(draft.id, state.drafts) || draft.origin !== 'human' || draft.processingAttemptId !== null || draft.sourceNoteRefId !== state.sourceBaseline.id || state.item.currentDraftId === null || draft.parentDraftId !== state.item.currentDraftId || draft.version !== state.drafts.length + 1) return failed('STALE_PIN', 'human revision must be a valid current-draft successor'); changes = { drafts: [...state.drafts, draft], approval: null, confirmation: null, currentValidation: null, item: { ...state.item, currentDraftId: draft.id } }; }
	if (input.kind === 'confirm_publication' || input.kind === 'reconfirm_publication') { if (!exactApproval(state, input) || !input.confirmationId || !input.destinationId || !input.destinationContractVersion || !input.confirmedBy || !input.confirmedAt || (input.kind === 'reconfirm_publication' && (state.confirmation === null || !validUtc(state.confirmation.confirmedAt) || state.confirmation.id === input.confirmationId || new Date(input.confirmedAt) <= new Date(state.confirmation.confirmedAt) || state.confirmation.destinationId !== input.destinationId || state.confirmation.destinationContractVersion !== input.destinationContractVersion))) return failed('STALE_PIN', 'explicit exact approval, destination contract and fresh human confirmation are required'); changes = { confirmation: { id: input.confirmationId, draftId: input.draftId!, reviewDecisionId: input.reviewDecisionId!, destinationId: input.destinationId, destinationContractVersion: input.destinationContractVersion, confirmedBy: input.confirmedBy, confirmedAt: input.confirmedAt } }; }
	if (input.kind === 'publish_succeeded' || input.kind === 'publish_failed') { const op = state.activeOperation; const attempt = input.publishAttempt; const confirmation = state.confirmation; if (!op || op.id !== input.operationId || op.kind !== 'publish' || !validEntity(attempt, state) || !attempt || !unused(attempt.id, state.publishAttempts) || attempt.sequence !== nextSequence(state.publishAttempts) || !confirmation || !state.approval || attempt.publicDraftId !== op.draftId || attempt.reviewDecisionId !== op.approvalId || attempt.destinationId !== op.destinationId || attempt.destinationContractVersion !== op.destinationContractVersion || attempt.confirmedBy !== confirmation.confirmedBy || attempt.confirmedAt !== confirmation.confirmedAt) return failed('ACTIVE_OPERATION_MISMATCH', 'publish completion must exactly match active approval and confirmation'); if (input.kind === 'publish_succeeded') { const record = input.publishedRecord; const draft = state.drafts.find((value) => value.id === attempt.publicDraftId); if (!record || !validEntity(record, state) || !unused(record.id, state.publishedRecords) || attempt.outcome.status !== 'succeeded' || !draft || record.publishAttemptId !== attempt.id || record.sourceNoteRefId !== draft.sourceNoteRefId || record.publicDraftId !== attempt.publicDraftId || record.reviewDecisionId !== attempt.reviewDecisionId || record.destinationId !== attempt.destinationId || record.destinationContractVersion !== attempt.destinationContractVersion || record.destinationReference !== attempt.outcome.destinationReference || record.destinationRevision !== attempt.outcome.destinationRevision || record.receiptHash !== attempt.outcome.receiptHash) return failed('STALE_PIN', 'success requires an exact immutable published record'); } else if (attempt.outcome.status !== 'failed' || input.publishedRecord) return failed('STALE_PIN', 'failure requires only failed attempt evidence'); changes = { publishAttempts: [...state.publishAttempts, attempt], publishedRecords: input.kind === 'publish_succeeded' ? [...state.publishedRecords, input.publishedRecord!] : state.publishedRecords, activeOperation: null }; }
	return { ok: true, state: withAudit(state, input, to, changes), duplicate: false };
}
