import assert from 'node:assert/strict';
import test from 'node:test';
import { LEGAL_TRANSITIONS, PUBLICATION_STAGES, transitionPublication, type PublicationStage, type PublicationWorkflowState, type TransitionInput } from '../src/domain/publication-state-machine';

const h = 'a'.repeat(64);
const h2 = 'b'.repeat(64);
const at = '2026-08-09T00:00:00.000Z';
const base = (): PublicationWorkflowState => ({ item: { id: 'item', correlationId: 'corr', version: 1, stage: 'pending', currentDraftId: null, updatedAt: at }, budgets: { repairs: 0, regenerations: 0 }, nextRecovery: null, activeOperation: null, sourceBaseline: { id: 'source', path: 'note.md', contentHash: h }, currentValidation: null, approval: null, confirmation: null, processingAttempts: [], drafts: [], reviewDecisions: [], publishAttempts: [], publishedRecords: [], sourceRevisionSignals: [], audit: [], receipts: {} });
const input = (kind: TransitionInput['kind'], version: number, extra: Partial<TransitionInput> = {}): TransitionInput => ({ id: `${kind}-${version}`, itemId: 'item', correlationId: 'corr', expectedVersion: version, kind, occurredAt: at, actorId: 'human', ...extra });
const ok = (state: PublicationWorkflowState, event: TransitionInput): PublicationWorkflowState => { const result = transitionPublication(state, event); assert.equal(result.ok, true, result.ok ? '' : result.message); return result.state; };
const draft = (id: string, version: number, origin: 'processing' | 'human' = 'processing') => ({ id, publicationItemId: 'item', correlationId: 'corr', sourceNoteRefId: 'source', version, parentDraftId: origin === 'human' ? 'draft-1' : null, origin, processingAttemptId: origin === 'processing' ? 'process-1' : null, createdAt: at, content: id, hashAlgorithm: 'sha-256' as const, contentHash: h });
const produced = (id = 'process-1', sequence = 1, kind: 'generate' | 'repair' | 'regenerate' = 'generate', inputDraftId: string | null = null, draftId = 'draft-1', passed = true) => ({ id, publicationItemId: 'item', correlationId: 'corr', sequence, kind, sourceNoteRefId: 'source', inputDraftId, startedAt: at, completedAt: at, outcome: { status: 'produced' as const, publicDraftId: draftId, validation: { passed, code: passed ? 'OK' : 'INVALID', summary: passed ? 'ok' : 'invalid' } } });
const failedAttempt = (id: string, sequence: number, kind: 'generate' | 'repair' | 'regenerate', inputDraftId: string | null) => ({ id, publicationItemId: 'item', correlationId: 'corr', sequence, kind, sourceNoteRefId: 'source', inputDraftId, startedAt: at, completedAt: at, outcome: { status: 'failed' as const, failure: { code: 'FAILED', summary: 'safe halt' } } });
const approve = (id = 'review-1', decision: 'approved' | 'changes-requested' = 'approved', draftId = 'draft-1', version = 1, hash = h) => ({ id, publicationItemId: 'item', correlationId: 'corr', publicDraftId: draftId, publicDraftVersion: version, publicDraftContentHash: hash, decision, reviewerId: 'human', decidedAt: at, summary: null, supersedesReviewDecisionId: null });
const confirmation = (id = 'confirm-1', confirmedAt = at) => ({ reviewDecisionId: 'review-1', draftId: 'draft-1', draftVersion: 1, draftHash: h, confirmationId: id, destinationId: 'website', destinationContractVersion: '1', confirmedBy: 'human', confirmedAt });
const publishAttempt = (status: 'succeeded' | 'failed', sequence = 1) => ({ id: `publish-${sequence}`, publicationItemId: 'item', correlationId: 'corr', sequence, publicDraftId: 'draft-1', reviewDecisionId: 'review-1', destinationId: 'website', destinationContractVersion: '1', confirmedBy: 'human', confirmedAt: at, startedAt: at, completedAt: at, outcome: status === 'succeeded' ? { status: 'succeeded' as const, destinationReference: 'post', destinationRevision: null, receiptHash: h } : { status: 'failed' as const, failure: { code: 'DOWN', summary: 'no write' } } });
const publishedRecord = () => ({ id: 'record-1', publicationItemId: 'item', correlationId: 'corr', publishAttemptId: 'publish-1', sourceNoteRefId: 'source', publicDraftId: 'draft-1', reviewDecisionId: 'review-1', destinationId: 'website', destinationContractVersion: '1', destinationReference: 'post', destinationRevision: null, receiptHash: h, publishedAt: at });
const select = () => ok(base(), input('select_publication', 1));
const processing = () => ok(select(), input('start_generation', 2, { operationId: 'op-1' }));
const validating = (passed = true) => ok(processing(), input('processing_produced', 3, { operationId: 'op-1', processingAttempt: produced('process-1', 1, 'generate', null, 'draft-1', passed), draft: draft('draft-1', 1) }));
const ready = () => ok(validating(), input('validation_passed', 4, { validation: { draftId: 'draft-1', draftVersion: 1, draftHash: h, passed: true, code: 'OK', summary: 'ok' } }));
const reviewing = () => ok(ready(), input('begin_review', 5));
const approved = () => ok(reviewing(), input('approve_review', 6, { reviewDecision: approve(), draftId: 'draft-1' }));
const publishReady = () => ok(approved(), input('confirm_publication', 7, confirmation()));
const publishing = () => ok(publishReady(), input('start_publish', 8, { operationId: 'publish-op', ...confirmation() }));
const publishFailed = () => ok(publishing(), input('publish_failed', 9, { operationId: 'publish-op', publishAttempt: publishAttempt('failed') }));
const assertLegal = (state: PublicationWorkflowState, kind: TransitionInput['kind'], extra: Partial<TransitionInput>, target: string, budgets = state.budgets) => { const before = structuredClone(state); const e = input(kind, state.item.version, extra); const result = transitionPublication(state, e); assert.equal(result.ok, true, kind); if (!result.ok) return; assert.equal(result.state.item.stage, target); assert.equal(result.state.item.version, before.item.version + 1); assert.equal(result.state.audit.length, before.audit.length + 1); assert.deepEqual(result.state.budgets, budgets); assert.equal(result.state.item.correlationId, before.item.correlationId); assert.ok(result.state.receipts[e.id]); assert.deepEqual(result.state.audit.at(-1)?.budgetsBefore, before.budgets); assert.deepEqual(result.state.audit.at(-1)?.budgetsAfter, budgets); };

test('documents a closed table with every canonical legal transition', () => {
	assert.equal(LEGAL_TRANSITIONS.length, 23);
	assert.equal(new Set(LEGAL_TRANSITIONS.map((row) => `${row.from}/${row.to}/${row.kind}`)).size, 23);
	for (const row of LEGAL_TRANSITIONS) assert.notEqual(row.from, 'published');
});

test('rejects every stage and trigger combination outside the legal table without effects', () => {
	const kinds: TransitionInput['kind'][] = ['select_publication', 'start_generation', 'processing_produced', 'processing_failed', 'validation_passed', 'validation_failed', 'start_repair', 'start_regeneration', 'begin_review', 'approve_review', 'submit_human_revision', 'request_changes', 'revise_approved_draft', 'confirm_publication', 'revise_confirmed_draft', 'start_publish', 'publish_succeeded', 'publish_failed', 'reconfirm_publication', 'escalate_publication_failure'];
	for (const stage of PUBLICATION_STAGES) for (const kind of kinds) {
		if (LEGAL_TRANSITIONS.some((row) => row.from === stage && row.kind === kind)) continue;
		const initial = { ...base(), item: { ...base().item, stage } };
		const result = transitionPublication(initial, input(kind, 1));
		assert.equal(result.ok, false, `${stage}/${kind}`);
		assert.equal(JSON.stringify(initial), JSON.stringify({ ...base(), item: { ...base().item, stage } }));
	}
});

test('happy path preserves immutable evidence through exactly one published record', () => {
	let state = base(); state = ok(state, input('select_publication', 1)); state = ok(state, input('start_generation', 2, { operationId: 'op-1' }));
	const produced = { id: 'process-1', publicationItemId: 'item', correlationId: 'corr', sequence: 1, kind: 'generate' as const, sourceNoteRefId: 'source', inputDraftId: null, startedAt: at, completedAt: at, outcome: { status: 'produced' as const, publicDraftId: 'draft-1', validation: { passed: true, code: 'OK', summary: 'ok' } } };
	state = ok(state, input('processing_produced', 3, { operationId: 'op-1', processingAttempt: produced, draft: draft('draft-1', 1) })); state = ok(state, input('validation_passed', 4, { validation: { draftId: 'draft-1', draftVersion: 1, draftHash: h, passed: true, code: 'OK', summary: 'ok' } })); state = ok(state, input('begin_review', 5));
	const review = { id: 'review-1', publicationItemId: 'item', correlationId: 'corr', publicDraftId: 'draft-1', publicDraftVersion: 1, publicDraftContentHash: h, decision: 'approved' as const, reviewerId: 'human', decidedAt: at, summary: null, supersedesReviewDecisionId: null };
	state = ok(state, input('approve_review', 6, { reviewDecision: review, draftId: 'draft-1' })); state = ok(state, input('confirm_publication', 7, { reviewDecisionId: 'review-1', draftId: 'draft-1', draftVersion: 1, draftHash: h, confirmationId: 'confirm-1', destinationId: 'website', destinationContractVersion: '1', confirmedBy: 'human', confirmedAt: at })); state = ok(state, input('start_publish', 8, { operationId: 'publish-op', reviewDecisionId: 'review-1', draftId: 'draft-1', draftVersion: 1, draftHash: h, confirmationId: 'confirm-1', destinationId: 'website', destinationContractVersion: '1' }));
	const attempt = { id: 'publish-1', publicationItemId: 'item', correlationId: 'corr', sequence: 1, publicDraftId: 'draft-1', reviewDecisionId: 'review-1', destinationId: 'website', destinationContractVersion: '1', confirmedBy: 'human', confirmedAt: at, startedAt: at, completedAt: at, outcome: { status: 'succeeded' as const, destinationReference: 'post-1', destinationRevision: null, receiptHash: h } };
	const record = { id: 'record-1', publicationItemId: 'item', correlationId: 'corr', publishAttemptId: 'publish-1', sourceNoteRefId: 'source', publicDraftId: 'draft-1', reviewDecisionId: 'review-1', destinationId: 'website', destinationContractVersion: '1', destinationReference: 'post-1', destinationRevision: null, receiptHash: h, publishedAt: at };
	state = ok(state, input('publish_succeeded', 9, { operationId: 'publish-op', publishAttempt: attempt, publishedRecord: record }));
	assert.equal(state.item.stage, 'published'); assert.equal(state.publishedRecords.length, 1); assert.equal(state.item.version, 10); assert.equal(state.audit.length, 9);
});

test('fails closed for non-enumerated, stale, correlation, operation, and conflicting duplicate inputs', () => {
	const state = base();
	assert.equal(transitionPublication(state, input('start_generation', 1, { operationId: 'x' })).ok, false);
	assert.equal(transitionPublication(state, input('select_publication', 2)).ok, false);
	assert.equal(transitionPublication(state, input('select_publication', 1, { correlationId: 'wrong' })).ok, false);
	const selected = ok(state, input('select_publication', 1));
	assert.equal(transitionPublication(selected, input('start_generation', 2)).ok, false);
	const duplicate = transitionPublication(selected, input('select_publication', 1)); assert.equal(duplicate.ok, true);
	const conflict = transitionPublication(selected, input('select_publication', 1, { evidence: 'different' })); assert.equal(conflict.ok, false);
});

test('source changes are orthogonal and never rewrite published history', () => {
	const state = { ...base(), item: { ...base().item, stage: 'published' as const } };
	const signal = { id: 'signal-1', publicationItemId: 'item', correlationId: 'corr', sourceNoteRefId: 'source', sequence: 1, kind: 'content-changed' as const, detectedAt: at, baselinePath: 'note.md', baselineContentHash: h, observedPath: 'note.md', observedContentHash: 'b'.repeat(64) };
	const next = ok(state, input('observe_source_revision', 1, { sourceRevisionSignal: signal }));
	assert.equal(next.item.stage, 'published'); assert.equal(next.sourceRevisionSignals.length, 1);
});

test('actually executes all 23 canonical legal rows with their target-specific effects', () => {
	const invalid = validating(false); const exhausted = { ...invalid, budgets: { repairs: 2, regenerations: 1 } };
	const repairing = ok(invalid, input('validation_failed', 4, { validation: { draftId: 'draft-1', draftVersion: 1, draftHash: h, passed: false, code: 'INVALID', summary: 'invalid' } }));
	const regeneration = { ...repairing, budgets: { repairs: 2, regenerations: 0 }, nextRecovery: 'regenerate' as const };
	const intervention = { ...validating(false), item: { ...validating(false).item, stage: 'needs_human_intervention' as const } };
	const rows: readonly [PublicationWorkflowState, TransitionInput['kind'], Partial<TransitionInput>, string, { repairs: number; regenerations: number }?][] = [
		[base(), 'select_publication', {}, 'selected'], [select(), 'start_generation', { operationId: 'op-1' }, 'processing'],
		[processing(), 'processing_produced', { operationId: 'op-1', processingAttempt: produced(), draft: draft('draft-1', 1) }, 'validating'], [processing(), 'processing_failed', { operationId: 'op-1', processingAttempt: failedAttempt('fail-1', 1, 'generate', null) }, 'needs_human_intervention'],
		[validating(), 'validation_passed', { validation: { draftId: 'draft-1', draftVersion: 1, draftHash: h, passed: true, code: 'OK', summary: 'ok' } }, 'review_ready'], [invalid, 'validation_failed', { validation: { draftId: 'draft-1', draftVersion: 1, draftHash: h, passed: false, code: 'INVALID', summary: 'invalid' } }, 'repairing'], [exhausted, 'validation_failed', { validation: { draftId: 'draft-1', draftVersion: 1, draftHash: h, passed: false, code: 'INVALID', summary: 'invalid' } }, 'needs_human_intervention'],
		[repairing, 'start_repair', { operationId: 'repair' }, 'processing', { repairs: 1, regenerations: 0 }], [regeneration, 'start_regeneration', { operationId: 'regenerate' }, 'processing', { repairs: 2, regenerations: 1 }], [ready(), 'begin_review', {}, 'in_review'], [reviewing(), 'approve_review', { reviewDecision: approve(), draftId: 'draft-1' }, 'approved'], [reviewing(), 'submit_human_revision', { draft: draft('human-2', 2, 'human') }, 'validating'],
		[reviewing(), 'request_changes', { reviewDecision: approve('change', 'changes-requested') }, 'repairing'], [{ ...reviewing(), budgets: { repairs: 2, regenerations: 1 } }, 'request_changes', { reviewDecision: approve('change', 'changes-requested') }, 'needs_human_intervention'], [approved(), 'revise_approved_draft', { draft: draft('human-2', 2, 'human') }, 'validating'], [approved(), 'confirm_publication', confirmation(), 'publish_ready'], [publishReady(), 'revise_confirmed_draft', { draft: draft('human-2', 2, 'human') }, 'validating'], [publishReady(), 'start_publish', { operationId: 'publish-op', ...confirmation() }, 'publishing'], [publishing(), 'publish_succeeded', { operationId: 'publish-op', publishAttempt: publishAttempt('succeeded'), publishedRecord: publishedRecord() }, 'published'], [publishing(), 'publish_failed', { operationId: 'publish-op', publishAttempt: publishAttempt('failed') }, 'publication_failed'], [publishFailed(), 'reconfirm_publication', confirmation('confirm-2', '2026-08-09T00:01:00.000Z'), 'publish_ready'], [publishFailed(), 'escalate_publication_failure', { evidence: { code: 'ESCALATED', summary: 'human' } }, 'needs_human_intervention'], [intervention, 'submit_human_revision', { draft: draft('human-2', 2, 'human') }, 'validating'],
	];
	assert.equal(rows.length, LEGAL_TRANSITIONS.length); rows.forEach(([state, kind, extra, target, budgets]) => assertLegal(state, kind, extra, target, budgets));
});

test('has complete recovery, review, publication, idempotency, source and pin evidence', () => {
	let state = validating(false);
	for (const [kind, id, attempt, nextDraft] of [['start_repair', 'repair-1', 'process-2', 'draft-2'], ['start_repair', 'repair-2', 'process-3', 'draft-3'], ['start_regeneration', 'regenerate-1', 'process-4', 'draft-4']] as const) {
		state = ok(state, input('validation_failed', state.item.version, { validation: { draftId: state.item.currentDraftId!, draftVersion: state.drafts.at(-1)!.version, draftHash: h, passed: false, code: 'INVALID', summary: 'invalid' } }));
		state = ok(state, input(kind, state.item.version, { operationId: id }));
		const attemptKind = kind === 'start_regeneration' ? 'regenerate' : 'repair'; state = ok(state, input('processing_produced', state.item.version, { operationId: id, processingAttempt: produced(attempt, state.processingAttempts.length + 1, attemptKind, state.drafts.at(-1)!.id, nextDraft, false), draft: { ...draft(nextDraft, state.drafts.length + 1), processingAttemptId: attempt, parentDraftId: state.item.currentDraftId } }));
	}
	state = ok(state, input('validation_failed', state.item.version, { validation: { draftId: 'draft-4', draftVersion: 4, draftHash: h, passed: false, code: 'INVALID', summary: 'invalid' } })); assert.equal(state.item.stage, 'needs_human_intervention'); assert.deepEqual(state.budgets, { repairs: 2, regenerations: 1 }); assert.equal(state.processingAttempts.length, 4); assert.equal(state.drafts.length, 4);
	const halted = ok(processing(), input('processing_failed', 3, { operationId: 'op-1', processingAttempt: failedAttempt('fail', 1, 'generate', null) })); assert.equal(halted.item.stage, 'needs_human_intervention');
	const beforeApproval = approved(); const revised = ok(beforeApproval, input('revise_approved_draft', 7, { draft: draft('human-2', 2, 'human') })); assert.equal(revised.approval, null); assert.equal(revised.confirmation, null); assert.equal(transitionPublication(beforeApproval, input('confirm_publication', 7, { ...confirmation(), draftHash: h2 })).ok, false);
	const failed = publishFailed(); assert.equal(failed.publishedRecords.length, 0); assert.equal(transitionPublication(failed, input('start_generation', 10, { operationId: 'never' })).ok, false); assert.equal(transitionPublication(failed, input('reconfirm_publication', 10, confirmation('confirm-1', '2026-08-09T00:01:00.000Z'))).ok, false); const reconfirmed = ok(failed, input('reconfirm_publication', 10, confirmation('confirm-2', '2026-08-09T00:01:00.000Z'))); assert.equal(ok(reconfirmed, input('start_publish', 11, { operationId: 'republish', ...confirmation('confirm-2', '2026-08-09T00:01:00.000Z') })).item.stage, 'publishing');
	const duplicateState = publishReady(); const first = duplicateState.audit[0]!; const duplicate = transitionPublication(duplicateState, { id: first.triggerId, itemId: 'item', correlationId: 'corr', expectedVersion: 1, kind: 'select_publication', occurredAt: at, actorId: 'human' }); assert.equal(duplicate.ok, true); if (duplicate.ok) { assert.equal(duplicate.duplicate, true); assert.strictEqual(duplicate.state, duplicateState); } assert.equal(transitionPublication(duplicateState, { id: first.triggerId, itemId: 'item', correlationId: 'corr', expectedVersion: 1, kind: 'select_publication', occurredAt: at, actorId: 'human', evidence: { code: 'mutated', summary: 'nested mutation' } }).ok, false);
	const source = (id: string, stage: PublicationStage) => ({ id, publicationItemId: 'item', correlationId: 'corr', sourceNoteRefId: 'source', sequence: 1, kind: 'content-changed' as const, detectedAt: at, baselinePath: 'note.md', baselineContentHash: h, observedPath: 'note.md', observedContentHash: h2 });
	for (const current of [base(), publishing(), { ...base(), item: { ...base().item, stage: 'needs_human_intervention' as const } }, { ...base(), item: { ...base().item, stage: 'published' as const }, publishedRecords: [publishedRecord()] }]) { const snapshot = structuredClone(current); const next = ok(current, input('observe_source_revision', current.item.version, { sourceRevisionSignal: source(`signal-${current.item.stage}`, current.item.stage) })); assert.equal(next.item.stage, current.item.stage === 'pending' ? 'needs_human_intervention' : current.item.stage); if (current.item.stage === 'published') assert.deepEqual(next.publishedRecords, snapshot.publishedRecords); assert.equal(next.audit.at(-1)?.kind, 'source_revision'); assert.equal(next.audit.at(-1)?.resultEvidence.type, 'source_revision_signal'); }
	const invalidSignal = base(); assert.equal(transitionPublication(invalidSignal, input('observe_source_revision', 1, { sourceRevisionSignal: { ...source('bad', 'pending'), sequence: 2, baselinePath: 'wrong' } })).ok, false);
	const confirmationAudit = publishReady().audit.at(-1)!; assert.equal(confirmationAudit.pins.confirmationId, 'confirm-1'); assert.equal(confirmationAudit.pins.destinationId, 'website'); assert.equal(confirmationAudit.pins.destinationContractVersion, '1'); assert.equal(confirmationAudit.resultEvidence.type, 'confirmation'); assert.equal(confirmationAudit.resultEvidence.confirmedBy, 'human'); assert.deepEqual(confirmationAudit.budgetsBefore, confirmationAudit.budgetsAfter);
});

test('rejects every material review, confirmation, operation and source pin mutation', () => {
	const reviewingState = reviewing(); for (const mutation of [{ publicDraftId: 'wrong' }, { publicDraftVersion: 2 }, { publicDraftContentHash: h2 }, { publicationItemId: 'other' }, { correlationId: 'wrong' }]) assert.equal(transitionPublication(reviewingState, input('approve_review', 6, { reviewDecision: { ...approve(), ...mutation }, draftId: 'draft-1' })).ok, false);
	const readyState = approved(); for (const mutation of [{ confirmationId: '' }, { reviewDecisionId: 'wrong' }, { draftId: 'wrong' }, { draftVersion: 2 }, { draftHash: h2 }]) assert.equal(transitionPublication(readyState, input('confirm_publication', 7, { ...confirmation(), ...mutation })).ok, false);
	const confirmedState = publishReady(); for (const mutation of [{ confirmationId: 'wrong' }, { destinationId: 'other' }, { destinationContractVersion: '2' }, { reviewDecisionId: 'wrong' }, { draftId: 'wrong' }]) assert.equal(transitionPublication(confirmedState, input('start_publish', 8, { operationId: 'publish-op', ...confirmation(), ...mutation })).ok, false);
	const processingState = processing(); for (const mutation of [{ operationId: 'wrong' }, { processingAttempt: { ...produced(), kind: 'repair' as const } }, { processingAttempt: { ...produced(), sequence: 2 } }, { processingAttempt: { ...produced(), sourceNoteRefId: 'wrong' } }, { processingAttempt: { ...produced(), inputDraftId: 'draft-1' } }]) assert.equal(transitionPublication(processingState, input('processing_produced', 3, { operationId: 'op-1', processingAttempt: produced(), draft: draft('draft-1', 1), ...mutation })).ok, false);
	const sourceState = base(); const source = { id: 'shape', publicationItemId: 'item', correlationId: 'corr', sourceNoteRefId: 'source', sequence: 1, kind: 'source-missing' as const, detectedAt: at, baselinePath: 'note.md', baselineContentHash: h, observedPath: null, observedContentHash: null }; for (const mutation of [{ observedPath: 'note.md' }, { observedContentHash: h }, { sourceNoteRefId: 'wrong' }, { baselineContentHash: h2 }]) assert.equal(transitionPublication(sourceState, input('observe_source_revision', 1, { sourceRevisionSignal: { ...source, ...mutation } })).ok, false);
});

test('records actual structured evidence and rejects exact nested and completion pin conflicts without effects', () => {
	const started = processing(); const producedInput = input('processing_produced', 3, { operationId: 'op-1', processingAttempt: produced(), draft: draft('draft-1', 1) }); const validatingState = ok(started, producedInput);
	const later = ok(validatingState, input('validation_passed', 4, { validation: { draftId: 'draft-1', draftVersion: 1, draftHash: h, passed: true, code: 'OK', summary: 'ok' } })); const duplicate = transitionPublication(later, producedInput); assert.equal(duplicate.ok, true); if (duplicate.ok) { assert.equal(duplicate.duplicate, true); assert.strictEqual(duplicate.state, later); }
	for (const mutation of [{ processingAttempt: { ...produced(), outcome: { ...produced().outcome, validation: { passed: true, code: 'MUTATED', summary: 'bad' } } } }, { draft: { ...draft('draft-1', 1), contentHash: h2 } }]) { const result = transitionPublication(later, { ...producedInput, ...mutation }); assert.equal(result.ok, false); if (!result.ok) assert.equal(result.code, 'DUPLICATE_CONFLICT'); }
	const validationBefore = validating(); for (const mutation of [{ draftVersion: 2 }, { draftHash: h2 }, { passed: false }, { code: 'WRONG' }, { summary: 'wrong' }]) { const snapshot = structuredClone(validationBefore); const result = transitionPublication(validationBefore, input('validation_passed', 4, { validation: { draftId: 'draft-1', draftVersion: 1, draftHash: h, passed: true, code: 'OK', summary: 'ok', ...mutation } })); assert.equal(result.ok, false); assert.deepEqual(validationBefore, snapshot); }
	const publishBefore = publishing(); const success = publishAttempt('succeeded'); const record = publishedRecord(); for (const mutation of [{ publishAttempt: { ...success, sequence: 2 } }, { publishAttempt: { ...success, publicDraftId: 'wrong' } }, { publishAttempt: { ...success, reviewDecisionId: 'wrong' } }, { publishAttempt: { ...success, destinationId: 'wrong' } }, { publishAttempt: { ...success, confirmedAt: '2026-08-09T00:01:00.000Z' } }, { publishAttempt: publishAttempt('failed') }, { publishedRecord: { ...record, publicationItemId: 'wrong' } }, { publishedRecord: { ...record, correlationId: 'wrong' } }, { publishedRecord: { ...record, sourceNoteRefId: 'wrong' } }, { publishedRecord: { ...record, destinationReference: 'wrong' } }, { publishedRecord: { ...record, receiptHash: h2 } }]) { const snapshot = structuredClone(publishBefore); const result = transitionPublication(publishBefore, input('publish_succeeded', 9, { operationId: 'publish-op', publishAttempt: success, publishedRecord: record, ...mutation })); assert.equal(result.ok, false); assert.deepEqual(publishBefore, snapshot); }
	const validationAudit = ready().audit.at(-1)!; assert.equal(validationAudit.resultEvidence.type, 'validation'); assert.equal(validationAudit.resultEvidence.status, 'passed'); const reviewAudit = approved().audit.at(-1)!; assert.equal(reviewAudit.resultEvidence.type, 'review_decision'); assert.equal(reviewAudit.resultEvidence.decision, 'approved'); const successAudit = ok(publishing(), input('publish_succeeded', 9, { operationId: 'publish-op', publishAttempt: success, publishedRecord: record })).audit.at(-1)!; assert.equal(successAudit.resultEvidence.type, 'publish_attempt'); assert.equal(successAudit.resultEvidence.outcomeStatus, 'succeeded'); const failureAudit = publishFailed().audit.at(-1)!; assert.equal(failureAudit.resultEvidence.code, 'DOWN'); assert.deepEqual(failureAudit.budgetsBefore, failureAudit.budgetsAfter);
	const pathSignal = { id: 'path', publicationItemId: 'item', correlationId: 'corr', sourceNoteRefId: 'source', sequence: 1, kind: 'path-changed' as const, detectedAt: at, baselinePath: 'note.md', baselineContentHash: h, observedPath: 'moved.md', observedContentHash: h }; assert.equal(ok(base(), input('observe_source_revision', 1, { sourceRevisionSignal: pathSignal })).item.stage, 'needs_human_intervention'); const unchangedContent = { ...pathSignal, id: 'unchanged', kind: 'content-changed' as const, observedPath: 'note.md', observedContentHash: h }; assert.equal(transitionPublication(base(), input('observe_source_revision', 1, { sourceRevisionSignal: unchangedContent })).ok, false);
});

test('fails closed for unknown source kinds and malformed or causally invalid timestamps', () => {
	const pathSignal = { id: 'unknown-kind', publicationItemId: 'item', correlationId: 'corr', sourceNoteRefId: 'source', sequence: 1, kind: 'path-changed' as const, detectedAt: at, baselinePath: 'note.md', baselineContentHash: h, observedPath: 'moved.md', observedContentHash: h };
	const unknownState = base(); const unknownSnapshot = structuredClone(unknownState); const unknown = transitionPublication(unknownState, input('observe_source_revision', 1, { sourceRevisionSignal: { ...pathSignal, kind: 'unknown-kind' } as unknown as typeof pathSignal })); assert.equal(unknown.ok, false); assert.deepEqual(unknownState, unknownSnapshot);
	const malformedState = base(); for (const mutation of [{ occurredAt: '2026-08-09' }, { occurredAt: 'not-a-date' }, { occurredAt: '2026-08-09T00:00:00+00:00' }]) { const snapshot = structuredClone(malformedState); assert.equal(transitionPublication(malformedState, input('select_publication', 1, mutation)).ok, false); assert.deepEqual(malformedState, snapshot); }
	const processState = processing(); for (const mutation of [{ startedAt: 'not-a-date' }, { completedAt: '2026-08-08T23:59:59.000Z' }]) { const snapshot = structuredClone(processState); assert.equal(transitionPublication(processState, input('processing_produced', 3, { operationId: 'op-1', processingAttempt: { ...produced(), ...mutation }, draft: draft('draft-1', 1) })).ok, false); assert.deepEqual(processState, snapshot); }
	const publishState = publishing(); for (const mutation of [{ confirmedAt: '2026-08-09T00:01:00.000Z' }, { completedAt: '2026-08-08T23:59:59.000Z' }]) { const snapshot = structuredClone(publishState); assert.equal(transitionPublication(publishState, input('publish_succeeded', 9, { operationId: 'publish-op', publishAttempt: { ...publishAttempt('succeeded'), ...mutation }, publishedRecord: publishedRecord() })).ok, false); assert.deepEqual(publishState, snapshot); }
	const recordState = publishing(); const lateAttempt = { ...publishAttempt('succeeded'), completedAt: '2026-08-09T00:01:00.000Z' }; assert.equal(transitionPublication(recordState, input('publish_succeeded', 9, { operationId: 'publish-op', publishAttempt: lateAttempt, publishedRecord: publishedRecord() })).ok, false);
	const failed = publishFailed(); const invalidStored = { ...failed, confirmation: { ...failed.confirmation!, confirmedAt: 'not-a-date' } }; assert.equal(transitionPublication(invalidStored, input('reconfirm_publication', 10, confirmation('confirm-2', '2026-08-09T00:01:00.000Z'))).ok, false); assert.equal(transitionPublication(failed, input('reconfirm_publication', 10, confirmation('confirm-2', 'not-a-date'))).ok, false);
});
